/*
 * Copyright (c) 2023 Alcosi Group Ltd. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.alcosi.lib.rabbit;

import com.alcosi.lib.logging.JavaLoggingLevel;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * RabbitProperties is a class that represents the configuration properties for RabbitMQ.
 * It is annotated with @ConfigurationProperties to specify the configuration prefix.
 */
@ConfigurationProperties("common-lib.rabbit")
public class RabbitProperties {
    /**
     * The disabled variable represents whether RabbitMQ is enabled or disabled.
     * It is a boolean variable in the RabbitProperties class.
     * <p>
     * By default, the disabled variable is set to false, indicating that RabbitMQ is enabled.
     * Developers can modify the value of the disabled variable to true if they want to disable RabbitMQ.
     * <p>
     * This variable is a member of the RabbitProperties class in the common-lib.rabbit package, which is
     * a configuration class for RabbitMQ with additional properties.
     */
    private Boolean disabled = false;
    /**
     * The maxLogBodySize variable represents the maximum size of the log body.
     * It is an integer variable in the RabbitProperties class.
     * <p>
     * By default, the maxLogBodySize variable is set to 10000, indicating that the maximum log body size is 10000 characters.
     * Developers can modify the value of the maxLogBodySize variable to specify a different maximum log body size.
     * <p>
     * This variable is a member of the RabbitProperties class in the common-lib.rabbit package, which is
     * a configuration class for RabbitMQ with additional properties.
     */
    private Integer maxLogBodySize = 10000;
    /**
     * The loggingLevel variable represents the logging level for the RabbitMQ application.
     * It is used to specify the verbosity of log messages that are generated by the application.
     * <p>
     * By default, the loggingLevel variable is set to "INFO", indicating that log messages with
     * the level "INFO" and above will be logged.
     * Developers can modify the value of the loggingLevel variable to change the logging verbosity.
     * <p>
     * This variable is a member of the RabbitProperties class in the common-lib.rabbit package,
     * which is a configuration class for RabbitMQ with additional properties.
     * The levels in descending order are:
     * SEVERE (highest value)
     * WARNING
     * INFO
     * CONFIG
     * FINE
     * FINER
     * FINEST (lowest value)
     */
    private JavaLoggingLevel loggingLevel =JavaLoggingLevel.INFO;

    public Integer getMaxLogBodySize() {
        return maxLogBodySize;
    }

    public void setMaxLogBodySize(Integer maxLogBodySize) {
        this.maxLogBodySize = maxLogBodySize;
    }

    public JavaLoggingLevel getLoggingLevel() {
        return loggingLevel;
    }

    public void setLoggingLevel(JavaLoggingLevel loggingLevel) {
        this.loggingLevel = loggingLevel;
    }

    public Boolean getDisabled() {
        return disabled;
    }

    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

}
